const refCode=new URLSearchParams(location.search).get("ref");if(refCode)localStorage.setItem("ksa_ref",refCode);
const KEY="kupsiapku_cart";
const APPS=[["zdravi","Moje zdraví","❤️"],["finance","Moje finance","🪙"],["portfolio","Moje portfolio","📈"],["cile","Moje cíle a góly","🎯"],["vztahy","Moje vztahy","💞"],["rozvoj","Můj rozvoj","🪷"],["firma","Moje firma","💼"],["podnikani","Moje podnikání","🚀"],["prace","Nová práce","🧭"]];
const allowed=new Set(APPS.map(x=>x[0]));
function normalize(x){return x==="investice"?"portfolio":x}
let legacy=[];try{legacy=JSON.parse(localStorage.getItem("ksa_cart")||"[]")}catch{}
let cart=[];try{cart=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{}
cart=[...new Set([...(Array.isArray(cart)?cart:[]),...(Array.isArray(legacy)?legacy:[])].map(normalize).filter(x=>allowed.has(x)))];
const save=()=>{localStorage.setItem(KEY,JSON.stringify(cart));localStorage.removeItem("ksa_cart");renderCart();window.dispatchEvent(new Event("storage"))};
window.add=function(id){id=normalize(id);if(allowed.has(id)&&!cart.includes(id))cart.push(id);save();document.querySelector("#checkout")?.scrollIntoView({behavior:"smooth"})};
window.remove=function(id){cart=cart.filter(x=>x!==normalize(id));save()};
function price(){return cart.length>=8?2990:cart.length===3?1290:cart.length*500}
function renderCart(){document.querySelectorAll("#count,[data-cart-count]").forEach(el=>el.textContent=cart.length);let el=document.querySelector("#cart");if(!el)return;if(!cart.length){el.innerHTML='<p class="sub">Košík je zatím prázdný.</p>';return}el.innerHTML=cart.map(id=>{let a=APPS.find(x=>x[0]===id);return '<div class="cartline"><span>'+a[2]+' '+a[1]+'</span><button type="button" onclick="remove(\''+id+'\')" aria-label="Odebrat '+a[1]+'">✕</button></div>'}).join("")+'<div class="total"><span>Celkem</span><span>'+price().toLocaleString("cs-CZ")+' Kč</span></div><p class="legal">Prodávající není plátcem DPH. DPH se neúčtuje.</p>'}
document.querySelector("#order")?.addEventListener("submit",e=>{e.preventDefault();if(!cart.length)return alert("Nejdřív vyber alespoň jednu aplikaci.");const fd=new FormData(e.target),o=Object.fromEntries(fd.entries());o.name=((o.firstName||"")+" "+(o.lastName||"")).trim();o.apps=[...cart];o.total=price();o.currency=o.currency||"CZK";o.servicePlan={baseAmount:199,baseCurrency:"CZK",interval:"month",provider:"gopay",status:"pending_activation"};o.ref=localStorage.getItem("ksa_ref")||"";o.payment="gopay_pending";o.number="KSA-"+Date.now();localStorage.setItem("ksa_last_order",JSON.stringify(o));document.querySelector("#receipt").innerHTML='<h3>Objednávka '+o.number+'</h3><p><b>'+o.name+'</b><br>'+o.email+(o.ref?'<br>Doporučení: '+o.ref:'')+'<br>'+o.street+', '+o.zip+' '+o.city+'</p>'+document.querySelector("#cart").innerHTML+'<button class="btn" onclick="window.print()">🖨️ Vytisknout rekapitulaci</button>';alert("Objednávka byla připravena. Online platba zatím není aktivní.");});
document.querySelector("#cookiesOk")?.addEventListener("click",()=>{localStorage.setItem("ksa_cookie","1");document.querySelector(".cookie")?.classList.add("hide")});if(localStorage.getItem("ksa_cookie"))document.querySelector(".cookie")?.classList.add("hide");save();
