window.KSA_BUILD="1664352-20260928-1607";
document.documentElement.dataset.ksaBuild=window.KSA_BUILD;
console.info("%cKUPSIAPKU BUILD","font-weight:bold;font-size:16px",window.KSA_BUILD,location.href);
console.info("KSA app.js loaded",{build:window.KSA_BUILD,script:document.currentScript?.src||"unknown",time:new Date().toISOString()});
const refCode=new URLSearchParams(location.search).get("ref");if(refCode)localStorage.setItem("ksa_ref",refCode);
const KEY="kupsiapku_cart";
const APPS=[["zdravi","Moje zdraví","❤️"],["finance","Moje finance","🪙"],["portfolio","Moje portfolio","📈"],["cile","Moje cíle a góly","🎯"],["vztahy","Moje vztahy","💞"],["rozvoj","Můj rozvoj","🪷"],["firma","Moje firma","💼"],["podnikani","Moje podnikání","🚀"],["prace","Nová práce","🧭"]];
const allowed=new Set(APPS.map(x=>x[0]));
function normalize(x){return x==="investice"?"portfolio":x}
let legacy=[];try{legacy=JSON.parse(localStorage.getItem("ksa_cart")||"[]")}catch{}
let cart=[];try{cart=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{}
cart=[...new Set([...(Array.isArray(cart)?cart:[]),...(Array.isArray(legacy)?legacy:[])].map(normalize).filter(x=>allowed.has(x)))];
const save=()=>{localStorage.setItem(KEY,JSON.stringify(cart));localStorage.removeItem("ksa_cart");renderCart();window.dispatchEvent(new Event("storage"))};
window.add=function(id){id=normalize(id);if(allowed.has(id)&&!cart.includes(id))cart.push(id);save();document.querySelector("#checkout")?.scrollIntoView({behavior:"smooth"})};
window.remove=function(id){cart=cart.filter(x=>x!==normalize(id));save()};
function price(){return cart.length>=8?2990:cart.length===3?1290:cart.length*500}
function renderCart(){document.querySelectorAll("#count,[data-cart-count]").forEach(el=>el.textContent=cart.length);let el=document.querySelector("#cart");if(!el)return;if(!cart.length){el.innerHTML='<p class="sub">Košík je zatím prázdný.</p>';return}el.innerHTML=cart.map(id=>{let a=APPS.find(x=>x[0]===id);return '<div class="cartline"><span>'+a[2]+' '+a[1]+'</span><button type="button" onclick="remove(\''+id+'\')" aria-label="Odebrat '+a[1]+'">✕</button></div>'}).join("")+'<div class="total"><span>Celkem</span><span>'+price().toLocaleString("cs-CZ")+' Kč</span></div><p class="legal">Prodávající není plátcem DPH. DPH se neúčtuje.</p>'}
const accountBox=document.querySelector('#checkoutAccount');
const accountPassword=document.querySelector('#accountPassword');
const accountNotice=document.querySelector('#checkoutAccountMessage');
function setAccountMode(){if(!accountPassword)return;const register=document.querySelector('input[name="accountMode"]:checked')?.value!=='login';accountPassword.minLength=register?8:0;accountPassword.autocomplete=register?'new-password':'current-password';document.querySelector('#accountPasswordLabel').textContent=register?'Nastavit heslo k účtu (alespoň 8 znaků) *':'Heslo k existujícímu účtu *';accountNotice.textContent='';}
document.querySelectorAll('input[name="accountMode"]').forEach(el=>el.addEventListener('change',setAccountMode));
async function authResponse(path,payload){const r=await fetch('/api/auth/'+path+'.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){if(path==='register'&&d.error==='EMAIL_EXISTS'){document.querySelector('input[name="accountMode"][value="login"]').checked=true;setAccountMode();throw new Error('Účet s tímto e-mailem již existuje. Zadejte jeho heslo, nebo použijte obnovu hesla.')}throw new Error(d.message||Object.values(d.fields||{})[0]||'Přihlášení nebo vytvoření účtu se nezdařilo.')}return d;}
async function csrfToken(orderData){const r=await fetch('/api/auth/me.php?checkout=20260929-account-1',{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));if(d.authenticated&&d.csrfToken)return d.csrfToken;
 const password=accountPassword?.value||'';const mode=document.querySelector('input[name="accountMode"]:checked')?.value||'register';if(!password)throw new Error('Zadejte heslo k účtu.');
 const auth=await authResponse(mode==='login'?'login':'register',mode==='login'?{email:orderData.email,password}:{firstName:orderData.firstName,lastName:orderData.lastName,email:orderData.email,phone:orderData.phone,password});
 if(!auth.csrfToken)throw new Error('Nepodařilo se vytvořit přihlášení.');
 sessionStorage.setItem('ksa_csrf',auth.csrfToken);accountPassword.value='';accountPassword.required=false;accountBox.hidden=true;return auth.csrfToken;
}
if(accountBox)fetch('/api/auth/me.php',{credentials:'same-origin',cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.authenticated){accountBox.hidden=true;accountPassword.required=false;}else{accountBox.hidden=false;accountPassword.required=true;}}).catch(()=>{});
const orderForm=document.querySelector('#order');
if(orderForm){orderForm.onsubmit=async e=>{e.preventDefault();e.stopImmediatePropagation();if(!cart.length)return alert('Nejdřív vyber alespoň jednu aplikaci.');const form=e.currentTarget;const submit=form.querySelector('button[type="submit"],input[type="submit"]');if(submit){submit.disabled=true;submit.textContent='Ukládám objednávku…'}const fd=new FormData(form),o=Object.fromEntries(fd.entries());delete o.accountMode;delete o.accountPassword;o.apps=[...cart];o.ref=localStorage.getItem('ksa_ref')||'';try{const csrf=await csrfToken(o);const r=await fetch('/api/orders/create.php?checkout=20260928-4',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(o)});const d=await r.json().catch(()=>({}));if(r.status===401){sessionStorage.removeItem('ksa_csrf');accountBox.hidden=false;accountPassword.required=true;throw new Error('Přihlášení vypršelo. Přihlaste se znovu u objednávky.')}if(r.status===403&&d.error==='CSRF_FAILED'){sessionStorage.removeItem('ksa_csrf');throw new Error('Bezpečnostní token vypršel. Odešlete objednávku znovu.')}if(!r.ok||!d.ok)throw new Error(d.message||('Objednávku se nepodařilo uložit (HTTP '+r.status+').'));const order=d.order;if(!order?.number)throw new Error('Server nevrátil číslo objednávky.');localStorage.setItem('ksa_last_order',JSON.stringify(order));cart=[];save();const receipt=document.querySelector('#receipt');if(receipt){receipt.innerHTML='<h3>✓ Objednávka '+order.number+' byla vytvořena</h3><p>Částka: <b>'+(order.totalMinor/100).toLocaleString('cs-CZ')+' '+order.currency+'</b><br>Stav: přijata – platba zatím není vyžadována.</p><p><a class="btn" href="/objednavky.html">Zobrazit moje objednávky</a></p>';receipt.scrollIntoView({behavior:'smooth'})}}catch(err){if(accountBox&&!accountBox.hidden){accountNotice.textContent=err.message||'Účet se nepodařilo připravit.';accountBox.scrollIntoView({behavior:'smooth'});}else alert(err.message||'Objednávku se nepodařilo uložit.');}finally{if(submit){submit.disabled=false;submit.textContent='Připravit objednávku →'}}};}
document.querySelector("#cookiesOk")?.addEventListener("click",()=>{localStorage.setItem("ksa_cookie","1");document.querySelector(".cookie")?.classList.add("hide")});if(localStorage.getItem("ksa_cookie"))document.querySelector(".cookie")?.classList.add("hide");save();
