<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/bootstrap.php';
require_once dirname(__DIR__).'/auth.php';
require_once dirname(__DIR__).'/checkout.php';
$user=current_session($pdo);
if(!$user){header('Location: /prihlaseni.html?next='.rawurlencode('/api/apps/cile.php'),true,302);exit;}
ensure_checkout_schema($pdo);
if(!has_active_product($pdo,(int)$user['id'],'cile')){header('Location: /moje-aplikace.html?access=denied&app=cile',true,302);exit;}
header('Cache-Control: private, no-store, no-cache, must-revalidate');header('X-Robots-Tag: noindex, nofollow');header('X-Frame-Options: DENY');header('X-Content-Type-Options: nosniff');
$first=htmlspecialchars((string)($user['first_name']??''),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
?><!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Moje cíle a góly | KupSiApku</title><link rel="stylesheet" href="/style.css?v=20260929-goals"><style>.goalForm{display:grid;gap:12px;margin:20px 0}.goalForm input,.goalForm textarea,.goalForm select{width:100%;padding:12px;border:1px solid #ccd2dc;border-radius:10px;font:inherit}.goalItem{display:grid;gap:8px;padding:16px;border-bottom:1px solid #e8ebef}.goalActions{display:flex;gap:8px;flex-wrap:wrap}.goalActions button{cursor:pointer}.muted{opacity:.7}.saveState{min-height:24px}</style></head><body><main class="accountMain"><section class="accountShell"><div class="eyebrow">Soukromá aplikace</div><h1>🎯 Moje cíle a góly</h1><p><?= $first!==''?'Ahoj '.$first.'. ':'' ?>Tvoje cíle se ukládají do tvého přihlášeného účtu.</p><form id="goalForm" class="goalForm"><input type="hidden" id="editId"><label>Název cíle<input id="title" maxlength="160" required></label><label>Horizont<select id="horizon"><option value="10y">10 let</option><option value="5y">5 let</option><option value="1y">1 rok</option><option value="1m">1 měsíc</option></select></label><label>Popis<textarea id="description" rows="3" maxlength="2000"></textarea></label><button class="btn" type="submit">Uložit cíl</button><button class="btn alt" id="cancelEdit" type="button" hidden>Zrušit úpravu</button></form><div id="saveState" class="saveState muted"></div><div class="accountPanel" id="goals"><div class="accountRow"><b>Načítám cíle…</b></div></div><div class="accountActions"><a class="btn alt" href="/moje-aplikace.html">← Moje aplikace</a></div></section></main><script>
(()=>{'use strict';const API='/api/apps/data.php?app=cile&key=goals';let goals=[];const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const labels={'10y':'10 let','5y':'5 let','1y':'1 rok','1m':'1 měsíc'};
async function request(method='GET',data){const r=await fetch(API,{method,credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify({data})});const d=await r.json().catch(()=>({}));if(r.status===401){location.href='/prihlaseni.html?next='+encodeURIComponent('/api/apps/cile.php');throw new Error('Přihlášení vypršelo.');}if(r.status===403){location.href='/moje-aplikace.html?access=denied&app=cile';throw new Error('Nemáte aktivní licenci.');}if(!r.ok||!d.ok)throw new Error(d.error||'Operace se nezdařila.');return d;}
function render(){const box=$('goals');if(!goals.length){box.innerHTML='<div class="accountRow"><b>Zatím nemáš žádný cíl.</b><span>Přidej první cíl formulářem nahoře.</span></div>';return;}box.innerHTML=goals.map(g=>'<div class="goalItem"><b>'+esc(g.title)+'</b><span>'+esc(labels[g.horizon]||g.horizon)+'</span>'+(g.description?'<span>'+esc(g.description)+'</span>':'')+'<div class="goalActions"><button class="btn alt" data-edit="'+esc(g.id)+'">Upravit</button><button class="btn alt" data-delete="'+esc(g.id)+'">Smazat</button></div></div>').join('');box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));}
async function load(){try{const d=await request();goals=Array.isArray(d.data)?d.data:[];render();$('saveState').textContent='Data načtena z tvého účtu.';}catch(e){$('saveState').textContent=e.message;}}
async function save(){ $('saveState').textContent='Ukládám…';await request('PUT',goals);$('saveState').textContent='Uloženo do tvého účtu.';}
function reset(){ $('goalForm').reset();$('editId').value='';$('cancelEdit').hidden=true;}
function edit(id){const g=goals.find(x=>x.id===id);if(!g)return;$('editId').value=g.id;$('title').value=g.title;$('horizon').value=g.horizon;$('description').value=g.description||'';$('cancelEdit').hidden=false;scrollTo({top:0,behavior:'smooth'});}
async function remove(id){if(!confirm('Opravdu smazat tento cíl?'))return;goals=goals.filter(x=>x.id!==id);try{await save();render();reset();}catch(e){$('saveState').textContent=e.message;await load();}}
$('goalForm').onsubmit=async e=>{e.preventDefault();const id=$('editId').value;const item={id:id||((crypto.randomUUID&&crypto.randomUUID())||String(Date.now())+Math.random()),title:$('title').value.trim(),horizon:$('horizon').value,description:$('description').value.trim(),updatedAt:new Date().toISOString()};if(!item.title)return;if(id){goals=goals.map(g=>g.id===id?item:g);}else goals.push(item);try{await save();render();reset();}catch(err){$('saveState').textContent=err.message;await load();}};$('cancelEdit').onclick=reset;load();})();
</script></body></html>