<?php
declare(strict_types=1);
// Restored server entry point; recovery configuration belongs in admin-config.php.
ini_set('display_errors','0');
set_exception_handler(static function(Throwable $error): void {
    error_log('Admin API failed: '.get_class($error));
    http_response_code(503);
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');
    echo json_encode(['ok'=>false,'error'=>'Administrace je dočasně nedostupná. Zkuste to později.'],JSON_UNESCAPED_UNICODE);
});
require __DIR__.'/bootstrap.php';
require __DIR__.'/admin-auth.php';
admin_auth_dispatch();
require_admin();
function status_value(array $data,array $allowed): string {$value=clean_string($data,'status',30);if(!in_array($value,$allowed,true))respond(['ok'=>false,'error'=>'Neplatný stav.'],422);return $value;}
if($method==='GET'&&$action==='dashboard'){$summary=['affiliates'=>(int)$pdo->query('SELECT COUNT(*) FROM affiliates')->fetchColumn(),'orders'=>(int)$pdo->query('SELECT COUNT(*) FROM orders')->fetchColumn(),'paidOrders'=>(int)$pdo->query('SELECT COUNT(*) FROM orders WHERE status="paid"')->fetchColumn(),'pendingPayouts'=>(int)$pdo->query('SELECT COUNT(*) FROM payout_requests WHERE status IN ("requested","approved")')->fetchColumn()];$affiliates=$pdo->query('SELECT a.id,a.code,a.first_name,a.last_name,a.email,a.phone,a.city,a.ico,a.bank_account,a.created_at,COUNT(DISTINCT r.id) referral_count,COALESCE(SUM(CASE WHEN r.status="paid" THEN r.commission_minor ELSE 0 END),0) commission_minor FROM affiliates a LEFT JOIN referrals r ON r.affiliate_id=a.id GROUP BY a.id ORDER BY a.id DESC LIMIT 200')->fetchAll();$orders=$pdo->query('SELECT id,order_number,customer_name,customer_email,total_minor,currency,referral_code,status,created_at,paid_at FROM orders ORDER BY id DESC LIMIT 200')->fetchAll();$payouts=$pdo->query('SELECT p.id,p.amount_minor,p.currency,p.status,p.requested_at,p.approved_at,p.paid_at,a.code,a.first_name,a.last_name,a.bank_account,i.invoice_number FROM payout_requests p JOIN affiliates a ON a.id=p.affiliate_id LEFT JOIN invoices i ON i.payout_request_id=p.id ORDER BY p.id DESC LIMIT 200')->fetchAll();respond(['ok'=>true,'summary'=>$summary,'affiliates'=>$affiliates,'orders'=>$orders,'payouts'=>$payouts]);}
if($method==='POST'&&$action==='order-status'){require_csrf();$data=json_input();$id=(int)($data['id']??0);$status=status_value($data,['awaiting_payment','paid','cancelled']);$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT order_number FROM orders WHERE id=?');$q->execute([$id]);$number=$q->fetchColumn();if(!$number)throw new RuntimeException('Objednávka nebyla nalezena.');$paidAt=$status==='paid'?gmdate('c'):null;$pdo->prepare('UPDATE orders SET status=?,paid_at=? WHERE id=?')->execute([$status,$paidAt,$id]);$refStatus=$status==='paid'?'paid':($status==='cancelled'?'cancelled':'pending');$pdo->prepare('UPDATE referrals SET status=? WHERE order_reference=?')->execute([$refStatus,$number]);$pdo->commit();respond(['ok'=>true,'message'=>'Stav objednávky a provize byl aktualizován.']);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();respond(['ok'=>false,'error'=>$e->getMessage()],422);}}
if($method==='POST'&&$action==='payout-status'){require_csrf();$data=json_input();$id=(int)($data['id']??0);$status=status_value($data,['requested','approved','paid','rejected']);$now=gmdate('c');$q=$pdo->prepare('UPDATE payout_requests SET status=?,approved_at=CASE WHEN ?="approved" AND approved_at IS NULL THEN ? ELSE approved_at END,paid_at=CASE WHEN ?="paid" THEN ? ELSE paid_at END WHERE id=?');$q->execute([$status,$status,$now,$status,$now,$id]);if($q->rowCount()===0)respond(['ok'=>false,'error'=>'Žádost o výplatu nebyla nalezena.'],404);respond(['ok'=>true,'message'=>'Stav výplaty byl aktualizován.']);}
if($method==='POST'&&$action==='affiliate-update'){require_csrf();$data=json_input();$id=(int)($data['id']??0);$email=strtolower(clean_string($data,'email'));if(!filter_var($email,FILTER_VALIDATE_EMAIL))respond(['ok'=>false,'error'=>'Zadejte platný e-mail.'],422);$values=[clean_string($data,'firstName',100),clean_string($data,'lastName',100),$email,clean_string($data,'phone',40),clean_string($data,'city',100),clean_string($data,'ico',20),clean_string($data,'bankAccount',60),$id];if($values[0]===''||$values[1]==='')respond(['ok'=>false,'error'=>'Jméno a příjmení jsou povinné.'],422);try{$q=$pdo->prepare('UPDATE affiliates SET first_name=?,last_name=?,email=?,phone=?,city=?,ico=?,bank_account=? WHERE id=?');$q->execute($values);$c=$pdo->prepare('SELECT 1 FROM affiliates WHERE id=?');$c->execute([$id]);if(!$c->fetchColumn())respond(['ok'=>false,'error'=>'Partner nebyl nalezen.'],404);respond(['ok'=>true,'message'=>'Účet partnera byl uložen.']);}catch(Throwable $e){respond(['ok'=>false,'error'=>'E-mail už používá jiný účet.'],409);}}
respond(['ok'=>false,'error'=>'Neznámá operace.'],404);
